server:
  port: 8089

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://10.40.33.174:3306/db_mall_trade?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver

